name: flutter_otp_input
description: "The OTPInput widget is a customizable Flutter widget that allows users to input a one-time password (OTP) through a series of individual text fields"
homepage: https://github.com/badiniibrahim/flutter_otp_input
repository: https://github.com/badiniibrahim/flutter_otp_input

version: 1.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
